#Goal: To perform testing in a GitHub Actions Pipeline by demonstrating a Py calc
name: GitHub Actions Testing

on:
  push:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
  
  
    steps:
      - name: To checkout the repo
        uses: actions/checkout@v4

    
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install testing Framework
        run: pip install pytest

  
      - name: Run tests
        run: pytest 


